### ISSUE TITLE
Style Widget Area better 

### ISSUE THREAD

**Issue by andrewlimaza** [andrewlimaza/ELI#19]
We need to style the widget area a little bit better. We should discuss the look and feel we want as the theme is a minimalist theme.

**Comment by travislima** [comment]
https://github.com/andrewlimaza/ELI/pull/31

**Comment by travislima** [comment]
Good to close?

**Comment by andrewlimaza** [comment]
Don't close, we still need to tweak styling and add `<hr>` in between widgets. Look at the widget area on Github for ideas. I like this styling.

**Comment by andrewlimaza** [comment]
Fixed in latest release, just added HR (border-top) to widget titles. Looked good though
