### ISSUE TITLE
Style comments.php better

### ISSUE THREAD

**Issue by andrewlimaza** [andrewlimaza/ELI#7]
Style the comments a bit better.

**Comment by jmfloor** [comment]
I'd like to give this a go. Going for a minimalistic feel. Any inputs?

**Comment by andrewlimaza** [comment]
Just work with Bootstrap 4.0 classes for fields etc. 

We need to neaten the following:

* Comment Form
* Comments on posts itself

I know Travis did a PR for button styling which I still need to test which may affect the comments form as well :)

**Comment by andrewlimaza** [comment]
Thanks Jo! 👍
